# Generated by Django 5.0.4 on 2024-07-11 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_project_members_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('time', models.IntegerField()),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='members_task', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='capstone.project')),
            ],
        ),
    ]
