# Generated by Django 5.0.4 on 2024-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_task_due_date_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
