# Generated by Django 5.0.4 on 2024-06-26 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wachlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='wachlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
